In [19]:
# utility file used to generate mzn data files from the dat files
import numpy as np
# open the file in Instances folder
f = open("Instances/inst21.dat", "r")
# the first line is the number of couriers
m = int(f.readline())
# the second line is the number of items
n = int(f.readline())
# the third line is the load size of each courier
load_size = [int(x) for x in f.readline().split()]
# the fourth line is the size of each item
item_size = [int(x) for x in f.readline().split()]
# the rest is the distance matrix
distance = []
for i in range(n+1):
    distance.append([int(x) for x in f.readline().split()])
# close the file
f.close()
print("couriers:", m)
print("items:", n)
print("load_size:", load_size)
print("item_size:", item_size)
# output the distance matrix as a numpy array
distance = np.array(distance)
print("distance:\n", distance)

# create a txt file to store the output formated as required
f = open("Instances/inst21.dzn", "w")
f.write("m = " + str(m) + ";" + "\n")
f.write("n = " + str(n) + ";" + "\n")
f.write("load_sizes = " + str(load_size) + ";" + "\n")
f.write("sizes = " + str(item_size) + ";" + "\n")
f.write("distances = [|")
for i in range(n+1):
    for j in range(n+1):
        if j>0:
            f.write(", ")
        f.write(str(distance[i][j]))
    if i == n:
        f.write("|];")    
    else:
        f.write("\n" + "|")
f.close()

couriers: 20
items: 143
load_size: [185, 190, 200, 180, 200, 190, 200, 180, 200, 190, 180, 190, 200, 180, 185, 180, 195, 190, 195, 190]
item_size: [9, 22, 10, 24, 25, 6, 22, 1, 19, 19, 5, 9, 8, 14, 4, 7, 10, 22, 17, 10, 8, 14, 12, 17, 19, 25, 25, 6, 21, 3, 19, 16, 21, 17, 19, 6, 10, 22, 17, 16, 5, 1, 21, 20, 6, 1, 11, 22, 25, 18, 9, 23, 17, 4, 1, 14, 11, 7, 21, 3, 18, 5, 6, 22, 13, 17, 5, 7, 1, 3, 10, 5, 1, 17, 14, 4, 10, 25, 11, 16, 25, 20, 3, 7, 2, 6, 14, 14, 2, 15, 22, 4, 22, 19, 5, 10, 4, 7, 11, 14, 2, 12, 12, 24, 8, 4, 25, 6, 9, 23, 15, 7, 6, 5, 12, 3, 22, 18, 16, 5, 1, 8, 20, 17, 11, 8, 15, 16, 6, 24, 10, 4, 10, 17, 5, 14, 16, 11, 25, 4, 12, 19, 6]
distance:
 [[  0  83  20 ...  86  65  58]
 [ 83   0  91 ...  16  60  79]
 [ 20  91   0 ... 106  73  66]
 ...
 [ 86  16 106 ...   0  76  95]
 [ 65  60  73 ...  76   0  19]
 [ 58  79  66 ...  95  19   0]]
