In [5]:
# Useful links: 
# https://developers.google.com/optimization/mip/mip_example

In [8]:
#!pip install ortools

In [95]:
# utility file used to generate mzn data files from the dat files
import numpy as np
# open the file in Instances folder
f = open("Instances/inst03.dat", "r")
# the first line is the number of couriers
m = int(f.readline())
# the second line is the number of items
n = int(f.readline())
# the third line is the load size of each courier
load_size = [int(x) for x in f.readline().split()]
# the fourth line is the size of each item
item_size = [int(x) for x in f.readline().split()]
# the rest is the distance matrix
distance = []
for i in range(n+1):
    distance.append([int(x) for x in f.readline().split()])
# close the file
f.close()
print("couriers:", m)
print("items:", n)
print("load_size:", load_size)
print("item_size:", item_size)
# output the distance matrix as a numpy array
distance = np.array(distance)
print("distance:\n", distance)

couriers: 3
items: 7
load_size: [15, 10, 7]
item_size: [3, 2, 6, 8, 5, 4, 4]
distance:
 [[0 3 3 6 5 6 6 2]
 [3 0 6 3 4 7 7 3]
 [3 4 0 7 6 3 5 3]
 [6 3 7 0 5 6 7 4]
 [5 4 6 3 0 3 3 3]
 [6 7 3 6 3 0 2 4]
 [6 7 5 6 3 2 0 4]
 [2 3 3 4 3 4 4 0]]


In [96]:
from ortools.linear_solver import pywraplp

def solve_courier_problem(courier_capacities, item_sizes, item_distances):
    num_couriers = len(courier_capacities)
    num_items = len(item_sizes)

    solver = pywraplp.Solver.CreateSolver('SCIP')

    # Create variables
    assignment = [[[solver.IntVar(0, 1, f'assignment_{i}_{j}_{k}') for j in range(num_items + 1)] for k in range(num_items + 1)] for i in range(num_couriers)]
    print('assignment =', assignment)
    
    # The diagonal of the matrix is 0
    solver.Add(sum(assignment[i][j][j] for i in range(num_couriers) for j in range(num_items + 1)) == 0)
    
    # Create constraints: each courier carries at least one item
    for i in range(num_couriers):
        solver.Add(sum(assignment[i][num_items][k] for k in range(num_items + 1)) >= 1)
    
    # Create constraints: items are assigned to at most one courier
    for j in range(num_items):
        solver.Add(sum(assignment[i][j][k] for i in range(num_couriers) for k in range(num_items + 1)) == 1)
    
    for j in range(num_items):
        solver.Add(sum(assignment[i][k][j] for i in range(num_couriers) for k in range(num_items + 1)) == 1)
    
    # Create constraint: n arcs in, n arcs out
    for i in range(num_couriers):
        for j in range(num_items + 1):
            solver.Add(sum(assignment[i][j][k] for k in range(num_items + 1)) == sum(assignment[i][k][j] for k in range(num_items + 1)))
    
    
    # Create constraint: courier capacities are respected
    for i in range(num_couriers):
        solver.Add(sum(assignment[i][j][k] * item_sizes[j] for j in range(num_items) for k in range(num_items + 1)) <= courier_capacities[i])
    
    # I create a variable max distance to minimize
    # the three lines below are a good beginning, but we want to also change the order of the items in the path so we need a way to express that
    max_distance = solver.NumVar(0, solver.infinity(), 'max_distance')
    for i in range(num_couriers):
        solver.Add(sum(assignment[i][j][k] * item_distances[j][k] for j in range(num_items + 1) for k in range(num_items + 1)) <= max_distance)
    
    solver.Minimize(max_distance)
    
    solver.set_time_limit(300000)
    #solver.EnableOutput()
    
    status = solver.Solve()

    if status == pywraplp.Solver.OPTIMAL:
        print('Solution:')
        for i in range(num_couriers):
            for j in range(num_items):
                for k in range(num_items + 1):
                    if assignment[i][j][k].solution_value() > 0:
                        print(f'Courier {i} takes item {j}')
        print('Max distance:', max_distance.solution_value())
        print('Objective value:', solver.Objective().Value())
        # I print the values of assignment
        # for each courier i create and print a item matrix
        print()
        for i in range(num_couriers):
            print(f'Courier {i} item matrix:')
            for j in range(num_items + 1):
                for k in range(num_items + 1):
                    print(int(assignment[i][j][k].solution_value()), end=' ')
                print()
            print()
        print(item_distances)
    else:
        print('The problem does not have an optimal solution.')

solve_courier_problem(load_size, item_size, distance)


assignment = [[[assignment_0_0_0, assignment_0_1_0, assignment_0_2_0, assignment_0_3_0, assignment_0_4_0, assignment_0_5_0, assignment_0_6_0, assignment_0_7_0], [assignment_0_0_1, assignment_0_1_1, assignment_0_2_1, assignment_0_3_1, assignment_0_4_1, assignment_0_5_1, assignment_0_6_1, assignment_0_7_1], [assignment_0_0_2, assignment_0_1_2, assignment_0_2_2, assignment_0_3_2, assignment_0_4_2, assignment_0_5_2, assignment_0_6_2, assignment_0_7_2], [assignment_0_0_3, assignment_0_1_3, assignment_0_2_3, assignment_0_3_3, assignment_0_4_3, assignment_0_5_3, assignment_0_6_3, assignment_0_7_3], [assignment_0_0_4, assignment_0_1_4, assignment_0_2_4, assignment_0_3_4, assignment_0_4_4, assignment_0_5_4, assignment_0_6_4, assignment_0_7_4], [assignment_0_0_5, assignment_0_1_5, assignment_0_2_5, assignment_0_3_5, assignment_0_4_5, assignment_0_5_5, assignment_0_6_5, assignment_0_7_5], [assignment_0_0_6, assignment_0_1_6, assignment_0_2_6, assignment_0_3_6, assignment_0_4_6, assignment_0_5_6, 