In [1]:
# utility file used to generate mzn data files from the dat files
import numpy as np
# open the file in Instances folder
f = open("inst05.dat", "r")
# the first line is the number of couriers
m = int(f.readline())
# the second line is the number of items
n = int(f.readline())
# the third line is the load size of each courier
load_size = [int(x) for x in f.readline().split()]
# the fourth line is the size of each item
item_size = [int(x) for x in f.readline().split()]
# the rest is the distance matrix
distance = []
for i in range(n+1):
    distance.append([int(x) for x in f.readline().split()])
# close the file
f.close()
print("couriers:", m)
print("items:", n)
print("load_size:", load_size)
print("item_size:", item_size)
# output the distance matrix as a numpy array
distance = np.array(distance)
print("distance:\n", distance)

# create a txt file to store the output formated as required
f = open("output.txt", "w")
f.write("m = " + str(m) + ";" + "\n")
f.write("n = " + str(n) + ";" + "\n")
f.write("load_sizes = " + str(load_size) + ";" + "\n")
f.write("sizes = " + str(item_size) + ";" + "\n")
f.write("distances = [|")
for i in range(n+1):
    for j in range(n+1):
        if j>0:
            f.write(", ")
        f.write(str(distance[i][j]))
    if i == n:
        f.write("|];")    
    else:
        f.write("\n" + "|")
f.close()

couriers: 2
items: 3
load_size: [18, 30]
item_size: [20, 17, 6]
distance:
 [[ 0 21 86 99]
 [21  0 71 80]
 [92 71  0 61]
 [59 80 61  0]]
